import { UnitData } from '../core/Types.ts';

// ─── Unit Templates ──────────────────────────────────────────────────────────
export const UnitDatabase: Record<string, UnitData> = {
  knight: {
    id: 'knight',
    name: 'Knight',
    className: 'knight',
    maxHP: 20,
    maxMP: 5,
    attack: 4,
    damageDice: '1d4',
    defense: 6,
    movementRange: 3,
    attackRange: 1,
    cost: 150,
    color: '#4488FF',
    abilities: [],
    passives: [],
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    className: 'archer',
    maxHP: 10,
    maxMP: 5,
    attack: 4,
    damageDice: '1d6',
    defense: 2,
    movementRange: 5,
    attackRange: 2,
    cost: 150,
    color: '#44CC44',
    abilities: [],
    passives: [],
  },
  mage: {
    id: 'mage',
    name: 'Mage',
    className: 'mage',
    maxHP: 10,
    maxMP: 5,
    attack: 6,
    damageDice: '1d10',
    defense: 2,
    movementRange: 4,
    attackRange: 2,
    cost: 150,
    color: '#AA44FF',
    abilities: [],
    passives: [],
  },
  thief: {
    id: 'thief',
    name: 'Thief',
    className: 'thief',
    maxHP: 15,
    maxMP: 5,
    attack: 4,
    damageDice: '1d6',
    defense: 2,
    movementRange: 6,
    attackRange: 1,
    cost: 150,
    color: '#FF8844',
    abilities: [],
    passives: [],
  },
  zoroark: {
    id: 'zoroark',
    name: 'Zoroark',
    className: 'zoroark',
    maxHP: 15,
    maxMP: 10,
    attack: 4,
    damageDice: '1d8',
    defense: 4,
    movementRange: 6,
    attackRange: 1,
    cost: 300,
    color: '#333333',
    abilities: ['darkSlash'],
    passives: [],
  },
  josuke: {
    id: 'josuke',
    name: 'Josuke',
    className: 'josuke',
    maxHP: 20,
    maxMP: 10,
    attack: 3,
    damageDice: '1d6',
    defense: 3,
    movementRange: 5,
    attackRange: 1,
    cost: 300,
    color: '#FF66AA',
    abilities: ['crazyDiamond'],
    passives: [],
  },
  pegasus: {
    id: 'pegasus',
    name: 'Pegasus Knight',
    className: 'pegasus',
    maxHP: 15,
    maxMP: 5,
    attack: 4,
    damageDice: '1d6',
    defense: 2,
    movementRange: 7,
    attackRange: 1,
    cost: 250,
    color: '#88CCFF',
    abilities: [],
    passives: ['flying'],
  },
  merfolk: {
    id: 'merfolk',
    name: 'Merfolk',
    className: 'merfolk',
    maxHP: 15,
    maxMP: 5,
    attack: 2,
    damageDice: '1d6',
    defense: 2,
    movementRange: 5,
    attackRange: 1,
    cost: 200,
    color: '#22AACC',
    abilities: [],
    passives: ['aquatic'],
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    className: 'skeleton',
    maxHP: 5,
    maxMP: 0,
    attack: 2,
    damageDice: '1d4',
    defense: 0,
    movementRange: 4,
    attackRange: 1,
    cost: 50,
    color: '#EEEEEE',
    abilities: [],
    passives: [],
  },
};

export function getUnitData(id: string): UnitData | undefined {
  return UnitDatabase[id];
}

export function getAllUnitData(): UnitData[] {
  return Object.values(UnitDatabase);
}
